#!/usr/bin/env php
<?php declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Arpegx\Bacup\Routing\Router;
use Arpegx\Bacup\Model\View;
use function Termwind\render;

$status_code = 0;

try {
    render(View::make("banner"));
    (new Router())->handle($argv);

} catch (\Exception $e) {
    render(View::make("exception", ["message" => $e->getMessage()]));
    $status_code = 1;

} finally {
    render(View::make("footer", ["version" => "v0.01"]));
    exit($status_code);
}