#!/usr/bin/env php
<?php declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Arpegx\Bacup\Routing\Router;

(new Router(["app" => $argv[0], "command" => $argv[1]]))->handle();