#!/usr/bin/env php
<?php declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Arpegx\Bacup\Model\IO;
use Arpegx\Bacup\Routing\Router;

$status_code = 0;

try {
    IO::render("banner");
    (new Router())->handle($argv);

} catch (\Exception $e) {
    IO::render("exception", ["message" => $e->getMessage()]);
    $status_code = 1;

} finally {
    IO::render("footer", ["version" => "v0.01"]);
    exit($status_code);
}