#!/usr/bin/env php
<?php declare(strict_types=1);

// declare filesystem structure to be included
$includes = [
  "file" => [
    "bacup",
  ],
  "directory" => [
    "app",
    "vendor",
    "data",
  ]
];

try {
  // build directory
  mkdir("build", 0700);

  // Create a new Phar object
  $phar = new Phar('build/bacup.phar');

  // Start
  $phar->startBuffering();

  // Set the default stub file
  $defaultStub = $phar->createDefaultStub('bacup');

  // Add files to the archive
  foreach ($includes["file"] as $file) {
    $phar->addFile($file);
  }

  foreach ($includes["directory"] as $directory) {
    $phar->buildFromIterator(new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS), __DIR__);
  }

  # Set shebang
  $phar->setStub("#!/usr/bin/env php \n" . $defaultStub);

  // Save the archive
  $phar->stopBuffering();

} catch (Exception $e) {
  echo 'Error: ' . $e->getMessage();
}